# Dredd config for Prism mock
color: true
loglevel: warning
language: nodejs
blueprint: ./openapi.dredd.yaml
path:
  - ./openapi.dredd.yaml
endpoint: http://127.0.0.1:4010
hookfiles: []
header:
  - 'Authorization: Bearer test-token'
