/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List enabled auth providers */
        get: operations["authProviders_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mobile/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate mobile OAuth PKCE flow
         * @description Creates an OAuth authorization attempt for mobile clients using PKCE.
         *     Returns an attempt_id to track the flow and an authorization_url to open in the browser.
         */
        post: operations["auth_mobile_authorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/mobile/attempts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check OAuth attempt status
         * @description Poll this endpoint to check if the OAuth flow has completed.
         *     Status transitions: pending → succeeded (with tokens) or failed/expired.
         */
        get: operations["auth_mobile_attempt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth callback handler
         * @description OAuth provider redirects here after user authorization.
         *     This endpoint exchanges the authorization code for tokens and updates the attempt status.
         *     For mobile flows, the user will be redirected back to the app via the redirect_uri.
         */
        get: operations["auth_callback_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user playlists */
        get: operations["playlists_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a playlist */
        get: operations["playlists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List playlist items (effective fields by default) */
        get: operations["playlists_items_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/active-playlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the active playlist pointer */
        get: operations["activePlaylist_get"];
        /** Set the active playlist */
        put: operations["activePlaylist_set"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/active-playlist/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append item to active playlist */
        post: operations["activePlaylist_addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/active-playlist/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove item from active playlist */
        delete: operations["activePlaylist_removeItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/migrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Migrate a playlist between providers */
        post: operations["jobs_requestMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job status/report */
        get: operations["jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream job progress updates */
        get: operations["jobs_events_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview a playlist file import */
        post: operations["imports_file_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export a playlist to file */
        post: operations["exports_enqueueFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{mbid}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow an artist by MBID */
        post: operations["artists_follow"];
        /** Unfollow artist */
        delete: operations["artists_unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{mbid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artist basics (bio + links) */
        get: operations["artists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{mbid}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artist relations */
        get: operations["artists_relations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example about:blank */
            type: string;
            /** @example provider_disabled */
            code: string;
            /** @example TIDAL is disabled */
            message: string;
            /**
             * @description Additional metadata for debugging, always includes request_id.
             * @example {
             *       "request_id": "req_abc123"
             *     }
             */
            details: {
                /** @description Correlates the server log entry for this error. */
                request_id: string | null;
            } & {
                [key: string]: unknown;
            };
        };
        FileImportPreviewResponse: {
            preview: components["schemas"]["PIFDocument"];
            counts: {
                tracks: number;
            };
        };
        PIFDocument: {
            name: string;
            description?: string | null;
            source_service?: ("spotify" | "deezer" | "tidal" | "youtube" | "amazon") | null;
            source_playlist_id?: string | null;
            tracks: components["schemas"]["PIFTrack"][];
        };
        PIFTrack: {
            position: number;
            title: string;
            artists: string[];
            album?: string | null;
            duration_ms?: number | null;
            explicit?: boolean | null;
            release_date?: string | null;
            isrc?: string | null;
            mb_recording_id?: string | null;
            mb_release_id?: string | null;
            provider_ids?: components["schemas"]["PIFProviderIds"] | null;
        };
        PIFProviderIds: {
            spotify_track_id?: string | null;
            deezer_track_id?: string | null;
            tidal_track_id?: string | null;
            youtube_video_id?: string | null;
            amazon_track_id?: string | null;
        };
        AuthProvider: {
            /** @enum {string} */
            name: "spotify" | "deezer" | "tidal" | "youtube";
        };
        PagedPlaylists: {
            data?: components["schemas"]["Playlist"][];
            next_cursor?: string | null;
        };
        Playlist: {
            id: number;
            name: string | null;
            provider?: string | null;
            provider_playlist_id?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        PagedPlaylistItems: {
            data?: components["schemas"]["PlaylistItemEffective"][];
            next_cursor?: string | null;
        };
        PlaylistItemEffective: {
            id: number;
            position: number | null;
            title: string;
            artists: string;
            album?: string | null;
            duration_ms?: number | null;
            recording_id?: number | null;
            isrc?: string | null;
            /** @example b8d0d7c0-8e1c-4b34-8bc3-38d78a0c2b1f */
            mb_recording_id?: string | null;
            /** @example b7a6d2e4-1c77-4a9f-9d5b-0c3b2ea0f4a1 */
            mb_release_id?: string | null;
            provider_track_id?: string | null;
        };
        ActivePlaylist: {
            playlist_id: number | null;
            /** Format: date-time */
            updated_at: string;
        };
        JobRef: {
            job_id: number;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
        };
        Job: {
            id: number;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            report?: {
                matched_isrc_pct?: number;
                matched_fuzzy_pct?: number;
                unresolved?: Record<string, never>[];
            };
            /** Format: uri */
            artifact_url?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string | null;
        };
        JobProgressUpdate: {
            job_id: number;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            percent?: number | null;
            message?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        Artist: {
            /** @example 123e4567-e89b-12d3-a456-426614174000 */
            mbid: string;
            name: string;
            bio?: {
                source?: string;
                summary?: string | null;
                /** Format: uri */
                url?: string | null;
            } | null;
            links?: {
                kind: string;
                /** Format: uri */
                url: string;
            }[];
            /** Format: date-time */
            updated_at?: string | null;
        };
        ArtistRelation: {
            /** @enum {string} */
            type: "influences" | "influenced_by" | "collaborated_with" | "member_of" | "has_members";
            artist: {
                /** @example abcdefab-1234-5678-90ab-abcdefabcdef */
                mbid: string;
                name: string;
            };
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Service unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Idempotency fingerprint conflict */
        IdempotencyConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unprocessable entity */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authProviders_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthProvider"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    auth_mobile_authorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description OAuth provider to authenticate with
                     * @enum {string}
                     */
                    provider: "spotify" | "deezer" | "tidal" | "youtube";
                    /** @description PKCE code challenge (SHA256 hash of code_verifier) */
                    code_challenge: string;
                    /**
                     * Format: uri
                     * @description Redirect URI (must match app scheme, e.g., pm://auth/callback)
                     * @example pm://auth/callback
                     */
                    redirect_uri: string;
                };
            };
        };
        responses: {
            /** @description Authorization attempt created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Unique attempt identifier to poll for completion
                         * @example att_abc123def456
                         */
                        attempt_id: string;
                        /**
                         * Format: uri
                         * @description URL to open in browser for user authentication
                         * @example https://accounts.spotify.com/authorize?client_id=...
                         */
                        authorization_url: string;
                        /**
                         * Format: date-time
                         * @description Expiration time for this attempt (typically 10 minutes)
                         */
                        expires_at: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    auth_mobile_attempt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The attempt_id returned from /auth/mobile/authorize */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attempt status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example att_abc123def456 */
                        attempt_id: string;
                        /**
                         * @description - pending: User has not completed authorization yet
                         *     - succeeded: Authorization complete, tokens available
                         *     - failed: Authorization was denied or encountered an error
                         *     - expired: Attempt expired (typically after 10 minutes)
                         * @enum {string}
                         */
                        status: "pending" | "succeeded" | "failed" | "expired";
                        /** @description Bearer token for API requests (only present when status=succeeded) */
                        access_token?: string | null;
                        /** @description Refresh token to obtain new access tokens (only present when status=succeeded) */
                        refresh_token?: string | null;
                        /** @description Access token lifetime in seconds (only present when status=succeeded) */
                        expires_in?: number | null;
                        /** @description Error code if status=failed */
                        error?: string | null;
                        /** @description Human-readable error description if status=failed */
                        error_description?: string | null;
                        /** Format: date-time */
                        created_at: string;
                        updated_at?: string | null;
                    };
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    auth_callback_handler: {
        parameters: {
            query?: {
                /** @description Authorization code from OAuth provider (present on success) */
                code?: string;
                /** @description State parameter to match the attempt (contains attempt_id for mobile flows) */
                state?: string;
                /** @description Error code if authorization failed */
                error?: string;
                /** @description Human-readable error description */
                error_description?: string;
            };
            header?: never;
            path: {
                /** @description OAuth provider handling this callback */
                provider: "spotify" | "deezer" | "tidal" | "youtube";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect back to application */
            302: {
                headers: {
                    /** @description Redirect URI (mobile app scheme or web URL) */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    playlists_list: {
        parameters: {
            query?: {
                provider?: "spotify" | "deezer" | "tidal" | "youtube";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedPlaylists"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    playlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 101 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    playlists_items_list: {
        parameters: {
            query?: {
                effective?: boolean;
                limit?: number;
                cursor?: string;
                order?: "position" | "added_at";
            };
            header?: never;
            path: {
                /** @example 101 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedPlaylistItems"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    activePlaylist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivePlaylist"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    activePlaylist_set: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    playlist_id: number;
                };
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    activePlaylist_addItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    recording_id: number;
                    /**
                     * @default append
                     * @enum {string}
                     */
                    position?: "append" | "head";
                } | {
                    isrc: string;
                    /**
                     * @default append
                     * @enum {string}
                     */
                    position?: "append" | "head";
                } | {
                    title: string;
                    primary_artist: string;
                    /**
                     * @default append
                     * @enum {string}
                     */
                    position?: "append" | "head";
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistItemEffective"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    activePlaylist_removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 4001 */
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    jobs_requestMigration: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Optional key to deduplicate POST attempts for 15 minutes. Reusing the same key with
                 *     the same request payload returns the original job reference; mismatched payloads
                 *     return HTTP 422 with code `idempotency_conflict`.
                 */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    source_provider: "spotify" | "deezer" | "tidal" | "youtube";
                    source_playlist_id: number;
                    /** @enum {string} */
                    dest_provider: "spotify" | "deezer" | "tidal" | "youtube";
                    dest_playlist_name?: string;
                };
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["IdempotencyConflict"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 5001 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    jobs_events_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 5001 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream delivering job progress updates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    imports_file_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
                "audio/x-mpegurl": string;
                "application/xspf+xml": string;
                "audio/x-scpls": string;
                "application/vnd.ms-wpl": string;
            };
        };
        responses: {
            /** @description Parsed playlist preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileImportPreviewResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    exports_enqueueFile: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Optional key to deduplicate POST attempts for 15 minutes. Reusing the same key with
                 *     the same request payload returns the original job reference; mismatched payloads
                 *     return HTTP 422 with code `idempotency_conflict`.
                 */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    playlist_id: number;
                    /** @enum {string} */
                    format: "m3u" | "xspf" | "csv";
                    /**
                     * @default lean
                     * @enum {string}
                     */
                    variant?: "lean" | "verbose";
                };
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRef"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["IdempotencyConflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    artists_follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 123e4567-e89b-12d3-a456-426614174000 */
                mbid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    artists_unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 123e4567-e89b-12d3-a456-426614174000 */
                mbid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    artists_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 123e4567-e89b-12d3-a456-426614174000 */
                mbid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artist"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    artists_relations: {
        parameters: {
            query?: {
                types?: ("influences" | "influenced_by" | "collaborated_with" | "member_of" | "has_members")[];
            };
            header?: never;
            path: {
                /** @example 123e4567-e89b-12d3-a456-426614174000 */
                mbid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ArtistRelation"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
