id: 09d_contract_schemathesis_prism
title: Schemathesis fuzz (CRUD-safe) against Prism
branch: codex/09d_contract_schemathesis_prism
overview: >
  Run Schemathesis property-based tests against the Prism mock to catch schema-level mistakes early.
  Restrict to GET/POST routes defined for v1 and mark POSTs as non-destructive (since Prism is stateless).
acceptance:
  - `pnpm test:contract:st:prism` runs and exits 0 locally
artifacts_to_touch:
  - package.json (scripts)
  - (optional) .schemathesis.toml
constraints:
  - Keep checks light (deadline 1s) to avoid flakiness in CI.
steps:
  - Add a Schemathesis config (.schemathesis.toml) with focused operations:

    [schemathesis]
    max_examples = 10

    [[operations]]
    method = "GET"
    path = "/playlists/{id}/items"

    [[operations]]
    method = "POST"
    path = "/exports/file"

    [[operations]]
    method = "POST"
    path = "/jobs/migrate"

  - Add scripts:

    {
      "scripts": {
        "test:contract:st:prism": "concurrently -k -s first \"pnpm mock:api\" \"wait-on tcp:4010 && schemathesis run openapi.yaml --base-url=http://127.0.0.1:4010 --checks all --experimental-openapi-3-1 --hypothesis-deadline=1000 --operations-file ./.schemathesis.toml\""
      }
    }

  - Note: Install Schemathesis via pipx in dev/CI image: `pipx install schemathesis`
